name: 'Terraform'

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  terraform:
    name: 'Terraform'
    runs-on: ubuntu-latest
    environment: production

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
         fetch-depth: 0  # Забираем всю историю

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Terraform Init
        run: |
          cd terraform
          terraform init

      - name: Terraform Plan
        env:
          TF_VAR_github_pat: ${{ secrets.PAT }}
          TF_VAR_deploy_key_pub: ${{ secrets.DEPLOY_KEY_PUB }}
        run: |
          cd terraform
          echo "create_develop_branch = true" > terraform.tfvars
          echo "github_pat = \"$TF_VAR_github_pat\"" >> terraform.tfvars
          echo "deploy_key_pub = \"$TF_VAR_deploy_key_pub\"" >> terraform.tfvars
          cat terraform.tfvars
          terraform plan

      - name: Terraform Apply
        if: github.ref == 'refs/heads/main' && github.event_name != 'pull_request'
        env:
          TF_VAR_github_pat: ${{ secrets.PAT }}
          TF_VAR_deploy_key_pub: ${{ secrets.DEPLOY_KEY_PUB }}
        run: |
          pwd
          cd terraform
          pwd
          echo "create_develop_branch = true" > terraform.tfvars
          echo "github_pat = \"$TF_VAR_github_pat\"" >> terraform.tfvars
          echo "deploy_key_pub = \"$TF_VAR_deploy_key_pub\"" >> terraform.tfvars
          ls -al
          cat terraform.tfvars
          terraform apply -auto-approve
