name: Notify Discord on Pull Request

on:
  pull_request:
    types:
      - opened

jobs:
  notify-discord:
    runs-on: ubuntu-latest
    steps:
      - name: Notify Discord about new PR
        uses: Ilshidur/sendToDiscord@v1.0.0
        with:
          webhook: ${{ secrets.DISCORD_WEBHOOK_URL }}
          message: |
            🛠️ **New Pull Request Created**

            **Author:** ${{ github.event.pull_request.user.login }}
            **Title:** ${{ github.event.pull_request.title }}
            **Description:** ${{ github.event.pull_request.body }}
            **Link:** [View Pull Request](${{ github.event.pull_request.html_url }})
